<a href="https://colab.research.google.com/github/harikamahapatra/linear-algebra-from-scratch/blob/main/LU_decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# starting matrix A
A = np.array([
    [2, 1, 1],
    [4, 3, 3],
    [8, 7, 9]
], dtype=float)

In [ ]:
# Identity matrix
E21 = np.eye(3)
# Set the multiplier at (row 1, col 0) -- Python is 0-indexed
E21[1, 0] = -2

# Apply E21 ( @ operator is the infix operator for the numpy.matmul)
A_step1 = E21 @ A
print(A_step1)

[[2. 1. 1.]
 [0. 1. 1.]
 [8. 7. 9.]]


In [ ]:
# E31 to clear the 8
E31 = np.eye(3)
E31[2, 0] = -4

# E32 to clear the remaining value in the 2nd column
# (Assuming A_step2 has a 3 in the (2,1) position and 1 in (1,1))
E32 = np.eye(3)
E32[2, 1] = -3

# Final U matrix
U = E32 @ E31 @ E21 @ A

In [ ]:
print(U)

[[2. 1. 1.]
 [0. 1. 1.]
 [0. 0. 2.]]


In [ ]:
#Finding L (The Inverse)
# L is the identity + the positive multipliers
L = np.eye(3)
L[1, 0] = 2  # Inverse of -2
L[2, 0] = 4  # Inverse of -4
L[2, 1] = 3  # Inverse of -3

In [ ]:
# The Check
A_reconstructed = L @ U

print("Original A:\n", A)
print("\nReconstructed L @ U:\n", A_reconstructed)


Original A:
 [[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]

Reconstructed L @ U:
 [[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]


In [ ]:
import numpy as np

def automatic_lu_solver():
    # 1. Get User Input
    n = int(input("Enter the size of the matrix (e.g., 3 for 3x3): "))
    print(f"Enter the entries for a {n}x{n} matrix row by row (space-separated):")

    entries = []
    for i in range(n):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        entries.append(row)

    A = np.array(entries)
    U = A.copy()
    L = np.eye(n)

    # 2. The Elimination Loop
    for i in range(n):
        for j in range(i + 1, n):
            # Calculate the multiplier for this specific position
            factor = U[j, i] / U[i, i]

            # Record the factor in L (this is the inverse step)
            L[j, i] = factor

            # Eliminate the value in U to make it Upper Triangular
            U[j, :] = U[j, :] - factor * U[i, :]

    # 3. Result
    print("\n--- Results ---")
    print("Matrix L (Lower):\n", L)
    print("\nMatrix U (Upper):\n", U)

    # Validation: L @ U must equal original A
    reconstructed = L @ U
    print("\nVerification (L @ U):\n", reconstructed)

    if np.allclose(A, reconstructed):
        print("\n SUCCESS")

# Run it
automatic_lu_solver()

Enter the size of the matrix (e.g., 3 for 3x3): 4
Enter the entries for a 4x4 matrix row by row (space-separated):
Row 1: 1 2 3 4
Row 2: 2 5 2 3
Row 3: 3 1 1 2
Row 4: 4 3 2 1

--- Results ---
Matrix L (Lower):
 [[ 1.          0.          0.          0.        ]
 [ 2.          1.          0.          0.        ]
 [ 3.         -5.          1.          0.        ]
 [ 4.         -5.          1.07142857  1.        ]]

Matrix U (Upper):
 [[  1.    2.    3.    4. ]
 [  0.    1.   -4.   -5. ]
 [  0.    0.  -28.  -35. ]
 [  0.    0.    0.   -2.5]]

Verification (L @ U):
 [[1. 2. 3. 4.]
 [2. 5. 2. 3.]
 [3. 1. 1. 2.]
 [4. 3. 2. 1.]]

 SUCCESS
